
name: CI
on:
  schedule:
    - cron: "0 1 * * *" 
  
  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: docs
          build_dir: assets/img/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
